//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int Id { get; set; }
        public string Activo { get; set; }
        public string Serial { get; set; }
        public string Nombre_Equipo { get; set; }
        public string Ip { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public System.DateTime Fecha_Fin_Garantia { get; set; }
        public int Id_Responsable { get; set; }
        public int Id_Area { get; set; }
        public int Id_Modelo { get; set; }
        public int Id_Sistema_Operativo { get; set; }
        public int Id_Propietario { get; set; }
        public int Id_Version_Office { get; set; }
        public int Id_Estado { get; set; }
    }
}
