//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int Id { get; set; }
        public string Activo { get; set; }
        public string Serial { get; set; }
        public string Nombre_Equipo { get; set; }
        public string Ip { get; set; }
        public string Comentario { get; set; }
        public long Fecha_Ingreso { get; set; }
        public long Fecha_Fin_Garantia { get; set; }
        public int Id_Responsable { get; set; }
        public int Id_Area { get; set; }
        public int Id_Modelo { get; set; }
        public int Id_Sistema_Operativo { get; set; }
        public int Id_Propietario { get; set; }
        public int Id_Version_Office { get; set; }
        public int Id_Estado { get; set; }
    }
}
