//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencia
    {
        public int Id { get; set; }
        public int Id_Tipo_Licencia { get; set; }
        public string Serial { get; set; }
        public long Fecha_Vencimiento { get; set; }
        public long Fecha_Compra { get; set; }
        public int Id_Equipo { get; set; }
    }
}
