//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int Id { get; set; }
        public int Id_Equipo { get; set; }
        public int Id_Usuario { get; set; }
        public string Id_Tipo_Mantenimiento { get; set; }
        public string Piezas_Instaladas { get; set; }
        public string Piezas_Retiradas { get; set; }
        public string Observaciones { get; set; }
    }
}
