//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_Marca { get; set; }
        public int Id_Tipo_Equipo { get; set; }
        public int Id_Estado { get; set; }
    }
}
