//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_Marca { get; set; }
        public int Id_Tipo_Equipo { get; set; }
        public int Id_Estado { get; set; }
    }
}
