//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Equipo { get; set; }
        public int Id_Area_Origen { get; set; }
        public int Id_Area_Destino { get; set; }
        public string Razon_Movimiento { get; set; }
        public int Id_Usuario { get; set; }
    }
}
