//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Equipo { get; set; }
        public int Id_Area_Origen { get; set; }
        public int Id_Area_Destino { get; set; }
        public string Razon_Movimiento { get; set; }
        public int Id_Usuario { get; set; }
    }
}
