//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Edificios
    {
        public int Id { get; set; }
        public string Sede { get; set; }
        public string Estado { get; set; }
        public string Nombre { get; set; }
        public int Id_Sede { get; set; }
        public int Id_Estado { get; set; }
        public int Id_Empresa { get; set; }
        public int Id_Ciudad { get; set; }
    }
}
