//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantoxWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Usuarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Contrasena { get; set; }
        public string Estado { get; set; }
        public string Rol { get; set; }
        public string Area { get; set; }
        public string Edificio { get; set; }
        public string Sede { get; set; }
        public string Empresa { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Sede { get; set; }
        public Nullable<int> Id_Edificio { get; set; }
        public int Id_Estado { get; set; }
        public int Id_Area { get; set; }
        public int Id_Rol { get; set; }
        public Nullable<int> Piso { get; set; }
    }
}
